env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
overrides: []
plugins:
  - '@typescript-eslint'
  - vue
rules: {}
